### PR TITLE
Define [com_interface] IID as string

### LINKED ISSUE #90: Consider writing GUIDs as strings in attribute macros
```rust
#[com_interface(EFF8970E-C50F-45E0-9284-291CE5A6F771)]
pub trait IAnimal: IUnknown { … }
```

This makes me uncomfortable. I’m half-expecting a formatter to reformat the GUID as `EFF8970E - C50F -45E0 -9284 -291CE5A6F771` or similar (rustfmt won’t now but could conceivably in the future), and some syntax highlighters *will* highlight parts of it differently, e.g. “9284” as a number but the rest not. Also, if lower-case hex is used (no idea whether it’s supported in theory or not), then some GUIDs will fail to tokenise, e.g. segments `0bd5` and `1ef3` won’t compile (invalid binary literal and invalid exponent, respectively).

I would prefer the GUID to be a string:

```rust
#[com_interface("EFF8970E-C50F-45E0-9284-291CE5A6F771")]
pub trait IAnimal: IUnknown { … }
```

`#[com_interface = "…"]` would also work.

### PR DESCRIPTION
**Pull request by Rantanen**
Define the GUID as a string in the `#[com_interface("<iid>")]` attributes.

Needed something easy and simple to work on. :)

Closes #90

### CODE REVIEW

**Comment by Rantanen** [comment]
The CI is private by the way. I forgot to run rustfmt on the changes, which resulted in a failing CI build, but all I get is access denied when trying to access it:
https://dev.azure.com/microsoft-rust/332945ff-0d35-4cde-b1e2-30e171b5154d/_build/results?buildId=353

**Comment by rylev** [comment]
@Rantanen awesome - thanks! Any way we could add a compile check to make sure we get a nice error message when not using a string literal?

**Comment by Rantanen** [comment]
Added that test and rebased on top of the master branch to resolve conflict in progress.rs and to fix the path tests, which need to use string GUIDs in this branch.

**Comment by Rantanen** [comment]
I don't really know what is causing the build failure here. I've tried replicating the `.azure-pipelines.yml` build locally and I can't get it to fail. I'll try fixing the timestamp on the last commit, which is at least confusing GitHub (since due to rebasing things, it's timestamp is before the second last commit).

**Comment by Rantanen** [comment]
There was an error in the tests. Apparently I had mixed the old pre-string path tests and this one when verifying that the errors were correct. Instead the new test failed to compile due to missing `use` and now because of non-string GUID parameter.

Fixed that and now the CI is green as well. Still no idea what the original issue was though. :|

**Pull request merged**
